# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0455522b267c69d5b4a734bfb1e5dde49adc20568aa63394524d83b05061999e3d07c8ef3c06b3b10ea668b9f664b1946017421cca83caf1fb879c305e103c31

test:
  secret_key_base: 861b3b095e623dadefcd631c225f22e6b92c4f46ecf56a1fba3dd457cb2df244b963578d1e7cefe14f14ebf8e7359361bb39e6067c4450063b51ffc02ff6be1f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
